# Generated by Django 2.0.1 on 2018-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=5)),
                ('quantity', models.CharField(max_length=10)),
                ('unstructured_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('servings', models.SmallIntegerField()),
                ('comments', models.TextField()),
                ('instructions', models.TextField()),
                ('image_url', models.URLField()),
                ('duration', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
    ]
